services:
  - type: web
    name: heart-failure-monitoring
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask --app run db upgrade && gunicorn run:app
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hf-monitoring-db
          property: connectionString
      - key: SENTRY_DSN
        sync: false
      - key: MAIL_SERVER
        value: smtp.sendgrid.net
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        value: apikey
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false

databases:
  - name: hf-monitoring-db
    plan: free
    databaseName: hfmonitoring
