"""add notifications_viewed_at to users

Revision ID: 5889500fa90d
Revises: e5ae00de9bdc
Create Date: 2026-04-29 22:35:29.689302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5889500fa90d'
down_revision = 'e5ae00de9bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_viewed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('notifications_viewed_at')

    # ### end Alembic commands ###
