"""initial schema with indexes

Revision ID: e5ae00de9bdc
Revises: 
Create Date: 2026-04-27 13:38:09.771540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ae00de9bdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Text(), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('base_weight', sa.Float(), nullable=True),
    sa.Column('base_weight_updated_at', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('Daily_Records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('breath_condition', sa.Integer(), nullable=False),
    sa.Column('alert_level', sa.Integer(), nullable=False),
    sa.Column('alert_logic_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_user_id', 'record_date')
    )
    with op.batch_alter_table('Daily_Records', schema=None) as batch_op:
        batch_op.create_index('ix_dr_parent_user_id', ['parent_user_id'], unique=False)
        batch_op.create_index('ix_dr_record_date', ['record_date'], unique=False)

    op.create_table('Invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('sharing_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sharing_token')
    )
    op.create_table('Watch_Relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('watcher_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['watcher_user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_user_id', 'watcher_user_id')
    )
    with op.batch_alter_table('Watch_Relationships', schema=None) as batch_op:
        batch_op.create_index('ix_wr_parent_user_id', ['parent_user_id'], unique=False)
        batch_op.create_index('ix_wr_watcher_user_id', ['watcher_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Watch_Relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_wr_watcher_user_id')
        batch_op.drop_index('ix_wr_parent_user_id')

    op.drop_table('Watch_Relationships')
    op.drop_table('Invitations')
    with op.batch_alter_table('Daily_Records', schema=None) as batch_op:
        batch_op.drop_index('ix_dr_record_date')
        batch_op.drop_index('ix_dr_parent_user_id')

    op.drop_table('Daily_Records')
    op.drop_table('Users')
    # ### end Alembic commands ###
